// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "阿公的旧时钟";

const lessonData = [
    // ===== 第1段 =====
    ["在", "zài", "in/at", "di"],
    ["马来西亚", "mǎ lái xī yà", "Malaysia", "Malaysia"],
    ["一个", "yī gè", "a", "sebuah"],
    ["渔村", "yú cūn", "fishing village", "kampung nelayan"],
    ["，", "", "", ""],
    ["住着", "zhù zhe", "lives", "tinggal"],
    ["一个", "yī gè", "a", "seorang"],
    ["叫", "jiào", "called", "bernama"],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["的", "de", "", ""],
    ["少年", "shào nián", "youth", "remaja"],
    ["。", "", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["的", "de", "", ""],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["常年", "cháng nián", "all year round", "sepanjang tahun"],
    ["在", "zài", "in", "di"],
    ["外地", "wài dì", "outstation", "luar kawasan"],
    ["工作", "gōng zuò", "work", "bekerja"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["从小", "cóng xiǎo", "since childhood", "sejak kecil"],
    ["由", "yóu", "by", "oleh"],
    ["阿公", "ā gōng", "grandfather", "datuk"],
    ["带大", "dài dà", "raised", "dibesarkan"],
    ["。", "", "", ""],
    ["阿公", "ā gōng", "grandfather", "datuk"],
    ["是", "shì", "is", "ialah"],
    ["个", "gè", "", ""],
    ["修", "xiū", "repair", "membaiki"],
    ["钟表", "zhōng biǎo", "clocks and watches", "jam dan watch"],
    ["的", "de", "", ""],
    ["老师傅", "lǎo shī fu", "old master", "tuan tua"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["村里", "cūn lǐ", "in the village", "di kampung"],
    ["开了", "kāi le", "opened", "membuka"],
    ["一间", "yī jiān", "a", "sebuah"],
    ["小小", "xiǎo xiǎo", "small", "kecil"],
    ["的", "de", "", ""],
    ["钟表店", "zhōng biǎo diàn", "clock shop", "kedai jam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["在", "zài", "at", "di"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["是", "shì", "is", "ialah"],
    ["个", "gè", "", ""],
    ["问题学生", "wèn tí xué shēng", "problem student", "pelajar bermasalah"],
    ["——", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["常常", "cháng cháng", "often", "selalu"],
    ["迟到", "chí dào", "late", "lewat"],
    ["，", "", "", ""],
    ["功课", "gōng kè", "schoolwork", "kerja sekolah"],
    ["也", "yě", "also", "juga"],
    ["不好", "bù hǎo", "not good", "tidak baik"],
    ["，", "", "", ""],
    ["别人", "bié rén", "others", "orang lain"],
    ["眼中", "yǎn zhōng", "eyes", "mata"],
    ["他", "tā", "he", "dia"],
    ["就是", "jiù shì", "is just", "hanyalah"],
    ["个", "gè", "", ""],
    ["不听话", "bù tīng huà", "disobedient", "tidak mendengar kata"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["班主任", "bān zhǔ rèn", "form teacher", "guru kelas"],
    ["林老师", "lín lǎo shī", "Teacher Lin", "Cikgu Lin"],
    ["曾经", "céng jīng", "once", "pernah"],
    ["看到", "kàn dào", "see", "melihat"],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["在", "zài", "after", "selepas"],
    ["放学", "fàng xué", "school ends", "tamat sekolah"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["蹲", "dūn", "squat", "mencangkung"],
    ["在", "zài", "at", "di"],
    ["路边", "lù biān", "roadside", "tepi jalan"],
    ["帮", "bāng", "help", "menolong"],
    ["一位", "yī wèi", "an", "seorang"],
    ["行动不便", "xíng dòng bù biàn", "immobile", "sukar bergerak"],
    ["的", "de", "", ""],
    ["老人", "lǎo rén", "elderly", "orang tua"],
    ["捡起", "jiǎn qǐ", "pick up", "memungut"],
    ["散落", "sàn luò", "scattered", "bertaburan"],
    ["一地", "yī dì", "all over the ground", "seluruh tanah"],
    ["的", "de", "", ""],
    ["杂物", "zá wù", "miscellaneous items", "barang-barang"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["想", "xiǎng", "want", "mahu"],
    ["帮帮", "bāng bāng", "help", "menolong"],
    ["这个", "zhè gè", "this", "ini"],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["有爱", "yǒu ài", "has love", "ada kasih"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["林老师", "lín lǎo shī", "Teacher Lin", "Cikgu Lin"],
    ["决定", "jué dìng", "decided", "memutuskan"],
    ["去", "qù", "go", "pergi"],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["家", "jiā", "home", "rumah"],
    ["家访", "jiā fǎng", "home visit", "lawatan rumah"],
    ["。", "", "", ""],
    ["走进", "zǒu jìn", "walk into", "masuk ke"],
    ["那间", "nà jiān", "that", "itu"],
    ["钟表店", "zhōng biǎo diàn", "clock shop", "kedai jam"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["看到", "kàn dào", "see", "melihat"],
    ["墙上", "qiáng shàng", "on the wall", "di dinding"],
    ["挂满", "guà mǎn", "hung all over", "penuh tergantung"],
    ["了", "le", "", ""],
    ["各式各样", "gè shì gè yàng", "various kinds", "pelbagai jenis"],
    ["的", "de", "", ""],
    ["旧时钟", "jiù shí zhōng", "old clocks", "jam lama"],
    ["，", "", "", ""],
    ["每一台", "měi yī tái", "each one", "setiap satu"],
    ["都", "dōu", "all", "semua"],
    ["在", "zài", "are", "sedang"],
    ["滴答滴答", "dī dā dī dā", "tick tock", "tik tok"],
    ["地", "de", "", ""],
    ["走着", "zǒu zhe", "moving", "berjalan"],
    ["。", "", "", ""],
    ["阿公", "ā gōng", "grandfather", "datuk"],
    ["坐在", "zuò zài", "sitting at", "duduk di"],
    ["工作台", "gōng zuò tái", "workbench", "meja kerja"],
    ["前", "qián", "front", "hadapan"],
    ["，", "", "", ""],
    ["戴", "dài", "wear", "memakai"],
    ["着", "zhe", "", ""],
    ["老花镜", "lǎo huā jìng", "reading glasses", "cermin mata tua"],
    ["，", "", "", ""],
    ["小心翼翼", "xiǎo xīn yì yì", "carefully", "berhati-hati"],
    ["地", "de", "", ""],
    ["修理", "xiū lǐ", "repair", "membaiki"],
    ["着", "zhe", "", ""],
    ["一台", "yī tái", "a", "sebuah"],
    ["怀表", "huái biǎo", "pocket watch", "jam poket"],
    ["。", "", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["则", "zé", "then", "manakala"],
    ["在", "zài", "at", "di"],
    ["一旁", "yī páng", "side", "sebelah"],
    ["静静", "jìng jìng", "quietly", "dengan senyap"],
    ["地", "de", "", ""],
    ["递", "dì", "pass", "menghulurkan"],
    ["工具", "gōng jù", "tools", "alat"],
    ["，", "", "", ""],
    ["动作", "dòng zuò", "movement", "gerakan"],
    ["熟练", "shú liàn", "skilful", "mahir"],
    ["而", "ér", "and", "dan"],
    ["温柔", "wēn róu", "gentle", "lembut"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["林老师", "lín lǎo shī", "Teacher Lin", "Cikgu Lin"],
    ["说明", "shuō míng", "explain", "menjelaskan"],
    ["来意", "lái yì", "purpose of visit", "tujuan lawatan"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["阿公", "ā gōng", "grandfather", "datuk"],
    ["叹", "tàn", "sighed", "mengeluh"],
    ["了", "le", "", ""],
    ["口气", "kǒu qì", "breath", "nafas"],
    ["，", "", "", ""],
    ["徐徐", "xú xú", "slowly", "perlahan"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["心里", "xīn lǐ", "in heart", "dalam hati"],
    ["苦", "kǔ", "bitter", "pahit"],
    ["。", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["三年", "sān nián", "three years", "tiga tahun"],
    ["没", "méi", "not", "tidak"],
    ["回来", "huí lái", "return", "pulang"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["嘴上", "zuǐ shàng", "mouth", "mulut"],
    ["不说", "bù shuō", "not say", "tidak berkata"],
    ["，", "", "", ""],
    ["可", "kě", "but", "tetapi"],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["晚上", "wǎn shàng", "night", "malam"],
    ["都", "dōu", "all", "semua"],
    ["会", "huì", "will", "akan"],
    ["看着", "kàn zhe", "looking at", "melihat"],
    ["墙上", "qiáng shàng", "on the wall", "di dinding"],
    ["的", "de", "", ""],
    ["时钟", "shí zhōng", "clock", "jam"],
    ["发呆", "fā dāi", "stare blankly", "terpinga-pinga"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["是", "shì", "is", "ialah"],
    ["在", "zài", "is", "sedang"],
    ["等", "děng", "wait", "menunggu"],
    ["，", "", "", ""],
    ["等", "děng", "wait", "menunggu"],
    ["时针", "shí zhēn", "hour hand", "jarum jam"],
    ["走到", "zǒu dào", "walk to", "berjalan ke"],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["回来", "huí lái", "return", "pulang"],
    ["的", "de", "", ""],
    ["那一天", "nà yī tiān", "that day", "hari itu"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["林老师", "lín lǎo shī", "Teacher Lin", "Cikgu Lin"],
    ["听", "tīng", "hear", "mendengar"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["一阵", "yī zhèn", "a burst of", "satu"],
    ["酸楚", "suān chǔ", "sadness", "kesedihan"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["想", "xiǎng", "want", "mahu"],
    ["为", "wèi", "for", "untuk"],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["做", "zuò", "do", "buat"],
    ["点什么", "diǎn shén me", "something", "sesuatu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["第二天", "dì èr tiān", "next day", "hari berikutnya"],
    ["，", "", "", ""],
    ["林老师", "lín lǎo shī", "Teacher Lin", "Cikgu Lin"],
    ["把", "bǎ", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["叫到", "jiào dào", "called to", "dipanggil ke"],
    ["办公室", "bàn gōng shì", "office", "pejabat"],
    ["，", "", "", ""],
    ["拿出", "ná chū", "take out", "mengeluarkan"],
    ["一个", "yī gè", "a", "sebuah"],
    ["自己", "zì jǐ", "own", "sendiri"],
    ["珍藏", "zhēn cáng", "treasured", "disimpan"],
    ["多年", "duō nián", "many years", "bertahun-tahun"],
    ["的", "de", "", ""],
    ["小闹钟", "xiǎo nào zhōng", "small alarm clock", "jam loceng kecil"],
    ["，", "", "", ""],
    ["温柔", "wēn róu", "gently", "lembut"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["，", "", "", ""],
    ["这个", "zhè gè", "this", "ini"],
    ["闹钟", "nào zhōng", "alarm clock", "jam loceng"],
    ["是", "shì", "is", "ialah"],
    ["我", "wǒ", "I", "saya"],
    ["小时候", "xiǎo shí hou", "childhood", "zaman kanak-kanak"],
    ["，", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["阿公", "ā gōng", "grandfather", "datuk"],
    ["送给", "sòng gěi", "gave", "memberi"],
    ["我", "wǒ", "me", "saya"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["阿公", "ā gōng", "grandfather", "datuk"],
    ["说", "shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["时间", "shí jiān", "time", "masa"],
    ["会", "huì", "will", "akan"],
    ["带走", "dài zǒu", "take away", "membawa pergi"],
    ["很多", "hěn duō", "many", "banyak"],
    ["东西", "dōng xi", "things", "benda"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["也", "yě", "also", "juga"],
    ["会", "huì", "will", "akan"],
    ["带来", "dài lái", "bring", "membawa"],
    ["很多", "hěn duō", "many", "banyak"],
    ["东西", "dōng xi", "things", "benda"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["是", "shì", "are", "ialah"],
    ["我", "wǒ", "my", "saya"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["重要", "zhòng yào", "important", "penting"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["之一", "zhī yī", "one of", "salah satu"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "jadi"],
    ["我", "wǒ", "I", "saya"],
    ["将", "jiāng", "", ""],
    ["这个", "zhè gè", "this", "ini"],
    ["闹钟", "nào zhōng", "alarm clock", "jam loceng"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["你", "nǐ", "you", "awak"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["知道", "zhī dào", "know", "tahu"],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "in", "dalam"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["遇到", "yù dào", "encounter", "menghadapi"],
    ["太多", "tài duō", "too many", "terlalu banyak"],
    ["的", "de", "", ""],
    ["不公平", "bù gōng píng", "unfairness", "ketidakadilan"],
    ["和", "hé", "and", "dan"],
    ["伤害", "shāng hài", "hurt", "kecederaan"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["你", "nǐ", "you", "awak"],
    ["有爱", "yǒu ài", "has love", "ada kasih"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["你", "nǐ", "you", "awak"],
    ["能", "néng", "can", "boleh"],
    ["挺过", "tǐng guò", "endure", "harungi"],
    ["一切", "yī qiè", "all", "segala"],
    ["风雨", "fēng yǔ", "storms", "badai"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["也", "yě", "also", "juga"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["你", "nǐ", "you", "awak"],
    ["有", "yǒu", "have", "ada"],
    ["能力", "néng lì", "ability", "keupayaan"],
    ["将", "jiāng", "", ""],
    ["诚恳", "chéng kěn", "sincere", "ikhlas"],
    ["的", "de", "", ""],
    ["爱", "ài", "love", "kasih"],
    ["传递", "chuán dì", "pass on", "menyampaikan"],
    ["给", "gěi", "to", "kepada"],
    ["更多", "gèng duō", "more", "lebih banyak"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["。", "", "", ""],
    ["你", "nǐ", "You", "Awak"],
    ["保留", "bǎo liú", "keep", "simpan"],
    ["这个", "zhè gè", "this", "ini"],
    ["闹钟", "nào zhōng", "alarm clock", "jam loceng"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membiarkan"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["爱", "ài", "love", "kasih"],
    ["和", "hé", "and", "dan"],
    ["力量", "lì liàng", "strength", "kekuatan"],
    ["守护", "shǒu hù", "protect", "melindungi"],
    ["你", "nǐ", "you", "awak"],
    ["。", "", "", ""],
    ["另外", "lìng wài", "in addition", "selain itu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["这儿", "zhè ér", "here", "di sini"],
    ["还有", "hái yǒu", "also have", "masih ada"],
    ["三张", "sān zhāng", "three", "tiga"],
    ["卡片", "kǎ piàn", "cards", "kad"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["写上", "xiě shàng", "write on", "tulis"],
    ["想", "xiǎng", "want", "mahu"],
    ["说", "shuō", "say", "berkata"],
    ["的", "de", "", ""],
    ["话", "huà", "words", "kata-kata"],
    ["，", "", "", ""],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["你", "nǐ", "you", "awak"],
    ["想", "xiǎng", "want", "mahu"],
    ["感谢", "gǎn xiè", "thank", "berterima kasih"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["，", "", "", ""],
    ["照亮", "zhào liàng", "illuminate", "menyinari"],
    ["其他", "qí tā", "other", "lain"],
    ["生命", "shēng mìng", "lives", "kehidupan"],
    ["吧", "ba", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["接过", "jiē guò", "received", "menerima"],
    ["闹钟", "nào zhōng", "alarm clock", "jam loceng"],
    ["，", "", "", ""],
    ["满心", "mǎn xīn", "full of heart", "penuh hati"],
    ["的", "de", "", ""],
    ["温暖", "wēn nuǎn", "warmth", "kehangatan"],
    ["涌上来", "yǒng shàng lái", "surged up", "membanjir"],
    ["，", "", "", ""],
    ["眼眶", "yǎn kuàng", "eye socket", "rongga mata"],
    ["红", "hóng", "red", "merah"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["从来", "cóng lái", "never", "tidak pernah"],
    ["没", "méi", "not", "tidak"],
    ["想过", "xiǎng guò", "thought", "terfikir"],
    ["，", "", "", ""],
    ["自己", "zì jǐ", "himself", "dirinya sendiri"],
    ["在", "zài", "in", "di"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["是", "shì", "is", "ialah"],
    ["“", "", "", ""],
    ["重要", "zhòng yào", "important", "penting"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["”", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["回到家", "huí dào jiā", "returned home", "pulang ke rumah"],
    ["，", "", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["思考", "sī kǎo", "think", "berfikir"],
    ["着", "zhe", "", ""],
    ["该", "gāi", "should", "patut"],
    ["把", "bǎ", "", ""],
    ["卡片", "kǎ piàn", "cards", "kad"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["谁", "shuí", "who", "siapa"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["了", "le", "", ""],
    ["邻居", "lín jū", "neighbour", "jiran"],
    ["——", "", "", ""],
    ["半工半读", "bàn gōng bàn dú", "work-study", "bekerja sambil belajar"],
    ["的", "de", "", ""],
    ["大学生", "dà xué shēng", "university student", "pelajar universiti"],
    ["阿明", "ā míng", "Ah Ming", "Ah Ming"],
    ["哥哥", "gē ge", "brother", "abang"],
    ["。", "", "", ""],
    ["阿明", "ā míng", "Ah Ming", "Ah Ming"],
    ["最近", "zuì jìn", "recently", "kebelakangan ini"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["工作", "gōng zuò", "work", "kerja"],
    ["压力", "yā lì", "pressure", "tekanan"],
    ["大", "dà", "big", "besar"],
    ["而", "ér", "and", "dan"],
    ["情绪", "qíng xù", "emotion", "emosi"],
    ["低落", "dī luò", "low", "murung"],
    ["，", "", "", ""],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["晚上", "wǎn shàng", "night", "malam"],
    ["都", "dōu", "all", "semua"],
    ["坐", "zuò", "sit", "duduk"],
    ["在", "zài", "at", "di"],
    ["走廊", "zǒu láng", "corridor", "koridor"],
    ["里", "lǐ", "in", "di"],
    ["发呆", "fā dāi", "stare blankly", "terpinga-pinga"],
    ["。", "", "", ""],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["走过去", "zǒu guò qù", "walk over", "berjalan ke sana"],
    ["，", "", "", ""],
    ["递给", "dì gěi", "hand to", "menghulurkan"],
    ["他", "tā", "him", "dia"],
    ["一张", "yī zhāng", "a", "satu"],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["，", "", "", ""],
    ["上面", "shàng miàn", "on it", "di atasnya"],
    ["写着", "xiě zhe", "written", "tertulis"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿明", "ā míng", "Ah Ming", "Ah Ming"],
    ["哥哥", "gē ge", "brother", "abang"],
    ["，", "", "", ""],
    ["谢谢", "xiè xiè", "thank you", "terima kasih"],
    ["你", "nǐ", "you", "awak"],
    ["上次", "shàng cì", "last time", "kali lepas"],
    ["帮", "bāng", "help", "tolong"],
    ["我", "wǒ", "me", "saya"],
    ["补习", "bǔ xí", "tuition", "tuisyen"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["很", "hěn", "very", "sangat"],
    ["努力", "nǔ lì", "hardworking", "berusaha"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["你", "nǐ", "you", "awak"],
    ["一定", "yī dìng", "surely", "pasti"],
    ["能", "néng", "can", "boleh"],
    ["渡过难关", "dù guò nán guān", "overcome difficulties", "mengharungi kesukaran"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["阿明", "ā míng", "Ah Ming", "Ah Ming"],
    ["读", "dú", "read", "baca"],
    ["了", "le", "", ""],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["，", "", "", ""],
    ["心里", "xīn lǐ", "in heart", "dalam hati"],
    ["暖暖", "nuǎn nuǎn", "warm", "hangat"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["给了", "gěi le", "gave", "memberi"],
    ["阿杰", "ā jié", "Ah Jie", "Ah Jie"],
    ["一个", "yī gè", "a", "satu"],
    ["拥抱", "yōng bào", "hug", "pelukan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["随后", "suí hòu", "afterwards", "selepas itu"],
    ["，", "", "", ""],
    ["阿明", "ā míng", "Ah Ming", "Ah Ming"],
    ["将", "jiāng", "", ""],
    ["另一张", "lìng yī zhāng", "another", "satu lagi"],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["了", "le", "", ""],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["黄先生", "huáng xiān shēng", "Mr. Wong", "Encik Wong"],
    ["，", "", "", ""],
    ["感谢", "gǎn xiè", "thank", "berterima kasih"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["在", "zài", "at", "pada"],
    ["他", "tā", "his", "dia"],
    ["最", "zuì", "most", "paling"],
    ["困难", "kùn nan", "difficult", "sukar"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "time", "masa"],
    ["给了", "gěi le", "gave", "memberi"],
    ["他", "tā", "him", "dia"],
    ["工作", "gōng zuò", "job", "kerja"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["对", "duì", "to", "bagi"],
    ["他", "tā", "him", "dia"],
    ["而言", "ér yán", "for", "bagi"],
    ["是", "shì", "is", "ialah"],
    ["莫大", "mò dà", "greatest", "terbesar"],
    ["的", "de", "", ""],
    ["恩惠", "ēn huì", "favour", "kurnia"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["向", "xiàng", "to", "kepada"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["承诺", "chéng nuò", "promise", "berjanji"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["会", "huì", "will", "akan"],
    ["和", "hé", "with", "dengan"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["渡过难关", "dù guò nán guān", "overcome difficulties", "mengharungi kesukaran"],
    ["。", "", "", ""],
    ["深受", "shēn shòu", "deeply", "sangat"],
    ["感动", "gǎn dòng", "moved", "terharu"],
    ["的", "de", "", ""],
    ["黄先生", "huáng xiān shēng", "Mr. Wong", "Encik Wong"],
    ["回到家", "huí dào jiā", "returned home", "pulang ke rumah"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["将", "jiāng", "", ""],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["放在", "fàng zài", "placed at", "diletakkan di"],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["的", "de", "", ""],
    ["枕边", "zhěn biān", "bedside", "sisi bantal"],
    ["，", "", "", ""],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["读", "dú", "read", "baca"],
    ["了", "le", "", ""],
    ["之后", "zhī hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["主动", "zhǔ dòng", "actively", "secara aktif"],
    ["抱住", "bào zhù", "hug", "memeluk"],
    ["了", "le", "", ""],
    ["爸爸", "bà ba", "father", "ayah"],
    ["——", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["是", "shì", "is", "ialah"],
    ["她", "tā", "she", "dia"],
    ["很久", "hěn jiǔ", "long time", "lama"],
    ["没", "méi", "not", "tidak"],
    ["做", "zuò", "done", "buat"],
    ["的", "de", "", ""],
    ["事", "shì", "thing", "perkara"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["这件事", "zhè jiàn shì", "this matter", "perkara ini"],
    ["就", "jiù", "then", "lalu"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["在", "zài", "in", "di"],
    ["村里", "cūn lǐ", "in the village", "di kampung"],
    ["一传十", "yī chuán shí", "spread from one to ten", "tersebar dari satu ke sepuluh"],
    ["，", "", "", ""],
    ["十传百", "shí chuán bǎi", "spread from ten to a hundred", "tersebar dari sepuluh ke seratus"],
    ["。", "", "", ""],
    ["后来", "hòu lái", "later", "kemudian"],
    ["，", "", "", ""],
    ["村里", "cūn lǐ", "in the village", "di kampung"],
    ["一位", "yī wèi", "a", "seorang"],
    ["名叫", "míng jiào", "named", "bernama"],
    ["张美华", "zhāng měi huá", "Zhang Meihua", "Zhang Meihua"],
    ["的", "de", "", ""],
    ["妇女", "fù nǚ", "woman", "wanita"],
    ["创办", "chuàng bàn", "founded", "menubuhkan"],
    ["了", "le", "", ""],
    ["“", "", "", ""],
    ["每月", "měi yuè", "every month", "setiap bulan"],
    ["一张", "yī zhāng", "one", "satu"],
    ["感谢卡", "gǎn xiè kǎ", "thank-you card", "kad penghargaan"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["活动", "huó dòng", "activity", "aktiviti"],
    ["，", "", "", ""],
    ["借此", "jiè cǐ", "thereby", "dengan itu"],
    ["来", "lái", "to", "untuk"],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["她", "tā", "her", "dia"],
    ["对", "duì", "to", "terhadap"],
    ["人们", "rén men", "people", "orang ramai"],
    ["的", "de", "", ""],
    ["赞美", "zàn měi", "praise", "pujian"],
    ["和", "hé", "and", "dan"],
    ["感谢", "gǎn xiè", "gratitude", "kesyukuran"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["不分", "bù fēn", "regardless of", "tanpa mengira"],
    ["年龄", "nián líng", "age", "umur"],
    ["、", "", "", ""],
    ["种族", "zhǒng zú", "race", "kaum"],
    ["、", "", "", ""],
    ["宗教", "zōng jiào", "religion", "agama"],
    ["或者", "huò zhě", "or", "atau"],
    ["社会地位", "shè huì dì wèi", "social status", "status sosial"],
    ["，", "", "", ""],
    ["每个人", "měi gè rén", "everyone", "setiap orang"],
    ["都", "dōu", "all", "semua"],
    ["需要", "xū yào", "need", "perlu"],
    ["得到", "dé dào", "receive", "mendapat"],
    ["肯定", "kěn dìng", "affirmation", "pengiktirafan"],
    ["、", "", "", ""],
    ["尊重", "zūn zhòng", "respect", "menghormati"],
    ["以及", "yǐ jí", "and", "serta"],
    ["赞许", "zàn xǔ", "approval", "persetujuan"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "oleh itu"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["每个", "měi gè", "every", "setiap"],
    ["星期", "xīng qī", "week", "minggu"],
    ["写", "xiě", "write", "tulis"],
    ["十张", "shí zhāng", "ten", "sepuluh"],
    ["卡片", "kǎ piàn", "cards", "kad"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["身边", "shēn biān", "beside", "sisi"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["，", "", "", ""],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["谢意", "xiè yì", "gratitude", "kesyukuran"],
    ["。", "", "", ""],
    ["两个", "liǎng gè", "two", "dua"],
    ["星期", "xīng qī", "weeks", "minggu"],
    ["内", "nèi", "within", "dalam"],
    ["，", "", "", ""],
    ["就", "jiù", "already", "sudah"],
    ["有", "yǒu", "have", "ada"],
    ["一百人", "yī bǎi rén", "one hundred people", "seratus orang"],
    ["收到", "shōu dào", "received", "menerima"],
    ["卡片", "kǎ piàn", "cards", "kad"],
    ["。", "", "", ""],
    ["很快", "hěn kuài", "quickly", "cepat"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["感谢卡", "gǎn xiè kǎ", "thank-you cards", "kad penghargaan"],
    ["在", "zài", "in", "di"],
    ["校园", "xiào yuán", "campus", "kampus"],
    ["和", "hé", "and", "dan"],
    ["社区", "shè qū", "community", "komuniti"],
    ["发挥", "fā huī", "exert", "memainkan"],
    ["了", "le", "", ""],
    ["效应", "xiào yìng", "effect", "kesan"],
    ["：", "", "", ""],
    ["学生", "xué shēng", "students", "pelajar"],
    ["的", "de", "", ""],
    ["成绩", "chéng jì", "results", "keputusan"],
    ["改善", "gǎi shàn", "improved", "bertambah baik"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["少年", "shào nián", "youths", "remaja"],
    ["的", "de", "", ""],
    ["自信", "zì xìn", "confidence", "keyakinan diri"],
    ["增强", "zēng qiáng", "increased", "meningkat"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["邻里", "lín lǐ", "neighbourhood", "kejiranan"],
    ["之间", "zhī jiān", "between", "antara"],
    ["的", "de", "", ""],
    ["关系", "guān xì", "relationship", "hubungan"],
    ["也", "yě", "also", "juga"],
    ["变得", "biàn de", "become", "menjadi"],
    ["融洽", "róng qià", "harmonious", "harmoni"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["从", "cóng", "From", "Daripada"],
    ["以上", "yǐ shàng", "above", "di atas"],
    ["两个", "liǎng gè", "two", "dua"],
    ["实例", "shí lì", "examples", "contoh"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["不难", "bù nán", "not difficult", "tidak sukar"],
    ["发现", "fā xiàn", "discover", "menemui"],
    ["小小", "xiǎo xiǎo", "small", "kecil"],
    ["一张", "yī zhāng", "a", "satu"],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["传达", "chuán dá", "convey", "menyampaikan"],
    ["了", "le", "", ""],
    ["一个", "yī gè", "a", "satu"],
    ["讯息", "xùn xī", "message", "mesej"],
    ["：", "", "", ""],
    ["每个人", "měi gè rén", "everyone", "setiap orang"],
    ["都", "dōu", "all", "semua"],
    ["有", "yǒu", "have", "ada"],
    ["其", "qí", "their", "ia"],
    ["可贵", "kě guì", "valuable", "berharga"],
    ["之处", "zhī chù", "aspect", "aspek"],
    ["，", "", "", ""],
    ["值得", "zhí dé", "worth", "layak"],
    ["他人", "tā rén", "others", "orang lain"],
    ["的", "de", "", ""],
    ["重视", "zhòng shì", "value", "menghargai"],
    ["和", "hé", "and", "dan"],
    ["尊重", "zūn zhòng", "respect", "menghormati"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["应", "yīng", "should", "harus"],
    ["不吝于", "bù lìn yú", "not stingy in", "tidak kedekut"],
    ["对", "duì", "to", "terhadap"],
    ["别人", "bié rén", "others", "orang lain"],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["感激", "gǎn jī", "gratitude", "kesyukuran"],
    ["与", "yǔ", "and", "dan"],
    ["赞美", "zàn měi", "praise", "pujian"],
    ["。", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["我们", "wǒ men", "we", "kita"],
    ["得到", "dé dào", "receive", "mendapat"],
    ["夸奖", "kuā jiǎng", "praise", "pujian"],
    ["和", "hé", "and", "dan"],
    ["肯定", "kěn dìng", "affirmation", "pengiktirafan"],
    ["，", "", "", ""],
    ["会", "huì", "will", "akan"],
    ["对", "duì", "to", "terhadap"],
    ["自己", "zì jǐ", "oneself", "diri sendiri"],
    ["充满", "chōng mǎn", "full of", "penuh"],
    ["信心", "xìn xīn", "confidence", "keyakinan"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["自然", "zì rán", "naturally", "secara semula jadi"],
    ["学会", "xué huì", "learn", "belajar"],
    ["去", "qù", "to", "untuk"],
    ["欣赏", "xīn shǎng", "appreciate", "menghargai"],
    ["他人", "tā rén", "others", "orang lain"],
    ["的", "de", "", ""],
    ["优点", "yōu diǎn", "strengths", "kelebihan"],
    ["，", "", "", ""],
    ["同时", "tóng shí", "at the same time", "pada masa yang sama"],
    ["更", "gèng", "more", "lebih"],
    ["容易", "róng yì", "easy", "mudah"],
    ["去", "qù", "to", "untuk"],
    ["称赞", "chēng zàn", "praise", "memuji"],
    ["别人", "bié rén", "others", "orang lain"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["今年", "jīn nián", "this year", "tahun ini"],
    ["教师节", "jiào shī jié", "Teachers' Day", "Hari Guru"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["将", "jiāng", "", ""],
    ["一张", "yī zhāng", "a", "satu"],
    ["小卡片", "xiǎo kǎ piàn", "small card", "kad kecil"],
    ["慎重", "shèn zhòng", "carefully", "dengan berhati-hati"],
    ["地", "de", "", ""],
    ["别在", "bié zài", "pinned on", "disematkan pada"],
    ["学生", "xué shēng", "students", "pelajar"],
    ["的", "de", "", ""],
    ["衣服", "yī fu", "clothes", "baju"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["有者", "yǒu zhě", "some", "sesetengah"],
    ["给予", "jǐ yǔ", "give", "memberi"],
    ["嘉许", "jiā xǔ", "commendation", "pujian"],
    ["，", "", "", ""],
    ["有者", "yǒu zhě", "some", "sesetengah"],
    ["给予", "jǐ yǔ", "give", "memberi"],
    ["鼓励", "gǔ lì", "encouragement", "galakan"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membuat"],
    ["他们", "tā men", "them", "mereka"],
    ["知道", "zhī dào", "know", "tahu"],
    ["他们", "tā men", "they", "mereka"],
    ["在", "zài", "in", "dalam"],
    ["我", "wǒ", "my", "saya"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["带来", "dài lái", "brought", "membawa"],
    ["的", "de", "", ""],
    ["改变", "gǎi biàn", "change", "perubahan"],
    ["。", "", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["在", "zài", "when", "apabila"],
    ["收到", "shōu dào", "received", "menerima"],
    ["卡片", "kǎ piàn", "cards", "kad"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["露出", "lù chū", "showed", "menunjukkan"],
    ["了", "le", "", ""],
    ["惊喜", "jīng xǐ", "pleasant surprise", "kejutan gembira"],
    ["、", "", "", ""],
    ["羞涩", "xiū sè", "shyness", "malu"],
    ["、", "", "", ""],
    ["开心", "kāi xīn", "happy", "gembira"],
    ["等", "děng", "etc", "dan lain-lain"],
    ["表情", "biǎo qíng", "expressions", "ekspresi"],
    ["。", "", "", ""],
    ["往后", "wǎng hòu", "afterwards", "selepas itu"],
    ["的", "de", "", ""],
    ["日子", "rì zi", "days", "hari-hari"],
    ["里", "lǐ", "in", "di"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["有", "yǒu", "have", "ada"],
    ["了", "le", "", ""],
    ["不同", "bù tóng", "different", "berbeza"],
    ["程度", "chéng dù", "degree", "tahap"],
    ["的", "de", "", ""],
    ["改变", "gǎi biàn", "change", "perubahan"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["开始", "kāi shǐ", "start", "mula"],
    ["学会", "xué huì", "learn", "belajar"],
    ["发现", "fā xiàn", "discover", "menemui"],
    ["别人", "bié rén", "others", "orang lain"],
    ["的", "de", "", ""],
    ["优点", "yōu diǎn", "strengths", "kelebihan"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["令", "lìng", "make", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["倍感", "bèi gǎn", "especially feel", "sangat merasa"],
    ["欣慰", "xīn wèi", "gratified", "lega"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["我们", "wǒ men", "We", "Kita"],
    ["不妨", "bù fáng", "might as well", "tidak salah"],
    ["效仿", "xiào fǎng", "emulate", "mencontohi"],
    ["张美华", "zhāng měi huá", "Zhang Meihua", "Zhang Meihua"],
    ["女士", "nǚ shì", "lady", "puan"],
    ["的", "de", "", ""],
    ["方式", "fāng shì", "way", "cara"],
    ["，", "", "", ""],
    ["送出", "sòng chū", "give out", "memberi keluar"],
    ["有形", "yǒu xíng", "tangible", "nyata"],
    ["或", "huò", "or", "atau"],
    ["无形", "wú xíng", "intangible", "tidak nyata"],
    ["的", "de", "", ""],
    ["卡片", "kǎ piàn", "cards", "kad"],
    ["，", "", "", ""],
    ["主动", "zhǔ dòng", "actively", "secara aktif"],
    ["地", "de", "", ""],
    ["向", "xiàng", "to", "kepada"],
    ["人", "rén", "people", "orang"],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["谢意", "xiè yì", "gratitude", "kesyukuran"],
    ["或", "huò", "or", "atau"],
    ["真诚", "zhēn chéng", "sincerely", "dengan ikhlas"],
    ["地", "de", "", ""],
    ["称许", "chēng xǔ", "praise", "memuji"],
    ["他人", "tā rén", "others", "orang lain"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membiarkan"],
    ["善", "shàn", "goodness", "kebaikan"],
    ["的", "de", "", ""],
    ["能量", "néng liàng", "energy", "tenaga"],
    ["在", "zài", "in", "di"],
    ["人群", "rén qún", "crowd", "orang ramai"],
    ["中", "zhōng", "in", "dalam"],
    ["传递", "chuán dì", "pass on", "menyampaikan"],
    ["。", "", "", ""],
    ["倘若", "tǎng ruò", "if", "jika"],
    ["人们", "rén men", "people", "orang ramai"],
    ["都", "dōu", "all", "semua"],
    ["能", "néng", "can", "boleh"],
    ["互相", "hù xiāng", "mutually", "saling"],
    ["赞美", "zàn měi", "praise", "memuji"],
    ["和", "hé", "and", "dan"],
    ["感恩", "gǎn ēn", "grateful", "bersyukur"],
    ["，", "", "", ""],
    ["那么", "nà me", "then", "maka"],
    ["社会", "shè huì", "society", "masyarakat"],
    ["将", "jiāng", "will", "akan"],
    ["呈现", "chéng xiàn", "present", "menunjukkan"],
    ["出", "chū", "", ""],
    ["一片", "yī piàn", "a", "satu"],
    ["祥和", "xiáng hé", "peaceful", "aman damai"],
    ["与", "yǔ", "and", "dan"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["的", "de", "", ""],
    ["氛围", "fēn wéi", "atmosphere", "suasana"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
